# -*- coding: utf-8 -*-
"""reservoir_navajo_trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQJsY4ZIiWNJTLUlbU631KhbtdGXCwUy
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install gym
!pip install stable-baselines3[extra]
!pip install tensorboard
# %load_ext tensorboard

import os
import io
import time
import random
import numpy as np
import pandas as pd
import torch as th
import gymnasium
from gymnasium import Env
from gymnasium.spaces import Box, Discrete
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common import results_plotter
from stable_baselines3.common.results_plotter import load_results, plot_results,ts2xy

# Loading the navajo reservoir dataset
# df_train=pd.read_csv('NAVAJORESERVOIR.csv')
# df_train=df_train.iloc[:,0:6]
# data_train=df_train.values
# data_train=data_train[0:22500,0:6]

class reservoir(Env):
    def __init__(self, data_train='/content/NAVAJORESERVOIR.csv')->None:
        """

        Args:
          data_train:
        """
        # Load dataset
        self.data = pd.read_csv(data_train)
        self.num_steps = len(self.data)
        self.current_step = 0

        # Define action and observation space
        self.action_space = Box(low=0.0, high=1, shape=(1,), dtype=np.float64)
        self.observation_space = Box(low=0.0, high=np.inf, shape=(4,), dtype=np.float64)

    def reset(self,seed=None)->float:
        """

        Args:
          seed:

        Returns:

        """
        self.current_step = 0
        info={}
        return self.data.iloc[self.current_step][['Elevation (feet)', 'Storage (af)', 'Evaporation (af)','Inflow** (cfs)']].values.astype(np.float64), info

    def step(self,action):
        """

        Args:
          action:

        Returns:

        """
        elevation = self.data.iloc[self.current_step]['Elevation (feet)']
        storage = self.data.iloc[self.current_step]['Storage (af)']
        inflow = self.data.iloc[self.current_step]['Inflow** (cfs)']
        evaporation = self.data.iloc[self.current_step]['Evaporation (af)']
        target_outflow_column = self.data['Total Release (cfs)']
        target_outflow = (target_outflow_column - target_outflow_column.min()) / (target_outflow_column.max() - target_outflow_column.min())
        target_outflow = target_outflow.iloc[self.current_step]

        predicted_outflow = action[0]

        # Compute reward (example: negative absolute difference from target)
        reward = -np.abs(predicted_outflow - target_outflow)

        # Move to the next time step
        self.current_step += 1
        done = self.current_step >= self.num_steps
        truncated=False
        info={}
        # Return observation, reward, done, info
        next_observation = self.data.iloc[self.current_step][['Elevation (feet)', 'Storage (af)', 'Evaporation (af)','Inflow** (cfs)']].values.astype(np.float64) if not done else None
        return next_observation, reward, done, truncated, info

    def render(self, mode='human')->None:
        """

        Args:
          mode:
        """
        pass

    def seed(self)->None:
        """

        """
        pass

    def close(self)->None:
        """

        """
        pass

data_train='/content/NAVAJORESERVOIR.csv'
env=reservoir(data_train)
check_env(env)

episodes =1
for episode in range(1,episodes+1):
  state, info=env.reset()
  print(state)
  done=False
  tot_reward=0
  while done==False:
    action=env.action_space.sample()
    state, reward, done, truncated, info=env.step(action)
    print(reward)
    tot_reward+=reward
  print('Episode: {}, Total reward: {}'.format(episode,tot_reward))

log_path=os.path.join('runs_navajo')
# env=Monitor(env, log_path)
agent=PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)
agent.learn(total_timesteps=2000000)

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir runs_navajo/PPO_4/

import os
import io
import time
import random
import numpy as np
import pandas as pd
import torch as th
import gymnasium
from gymnasium import Env
from gymnasium.spaces import Box, Discrete
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common import results_plotter
from stable_baselines3.common.results_plotter import load_results, plot_results,ts2xy
from sklearn.preprocessing import StandardScaler

# Load the data
df = pd.read_csv('/content/NAVAJORESERVOIR.csv')

# Extract features and targets
features = df[['Elevation (feet)', 'Storage (af)', 'Evaporation (af)', 'Inflow** (cfs)']]
targets = df['Total Release (cfs)']

# Scale the features
scaler_x = StandardScaler()
features_scaled = scaler_x.fit_transform(features)

# Scale the targets
scaler_y = StandardScaler()
targets_scaled = scaler_y.fit_transform(targets.values.reshape(-1, 1)).flatten()

# Create train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features_scaled, targets_scaled, test_size=0.2, random_state=42)


class ReservoirEnv(Env):
    def __init__(self, X_train, y_train):
        super(ReservoirEnv, self).__init__()
        self.X_train = X_train
        self.y_train = y_train
        self.current_step = 0
        self.action_space = Box(low=np.array([0]), high=np.array([1]), dtype=np.float32)
        self.observation_space = Box(low=np.array([-1.0, -1.0, -1.0, -1.0]), high=np.array([1.0, 1.0, 1.0, 1.0]), dtype=np.float32)

    def reset(self,seed=None):
        self.current_step = 0
        info={}
        if seed is not None:
            np.random.seed(seed)
        return self.X_train[self.current_step].astype(np.float32),info

    def step(self, action):
        self.current_step += 1
        done = self.current_step >= len(self.X_train)  # Check if we're done before incrementing current_step
        if not done:  # Calculate reward only if not done
            # Explicitly cast observation to float32
            observation = self.X_train[self.current_step].astype(np.float32)
            reward = -np.abs(action - self.y_train[self.current_step])
            # Convert reward to a float
            reward = float(reward)  # Ensure reward is a float
        else:  # If done, set observation and reward to defaults
            observation = np.zeros(self.observation_space.shape, dtype=np.float32)
            reward = 0.0  # Or any other appropriate default reward

        truncated=False
        info={}
        return observation, reward, done, truncated, info

    def render(self, mode='human'):
        pass

    def seed(self):
        pass

    def close(self):
        pass

# Create the environment
env = ReservoirEnv(X_train, y_train)
check_env(env)
log_path=os.path.join('runs_navajo')
# env=Monitor(env, log_path)
agent=PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)
agent.learn(total_timesteps=400000)

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir runs_navajo/PPO_1/

# Make predictions
predictions_scaled = agent.predict(X_test)[0]
predictions = scaler_y.inverse_transform(predictions_scaled.reshape(-1, 1)).flatten()

# Example of how to rescale a single prediction
example_scaled = agent.predict(X_test[0].reshape(1, -1))[0]
example_prediction = scaler_y.inverse_transform(example_scaled.reshape(-1, 1)).flatten()